### ISSUE TITLE
Building on OSX

### ISSUE THREAD

**Issue by drewpotter** [advancingu/QmlOgre#2]
When building on OSX I get the following errors:

/lib/ogreengine.cpp:101: error: use of undeclared identifier 'GL_ATOMIC_COUNTER_BUFFER'
    m_ogreContext->functions()->glBindBuffer(GL_ATOMIC_COUNTER_BUFFER, 0);

lib/ogreengine.cpp:104: error: use of undeclared identifier 'GL_DRAW_INDIRECT_BUFFER'
    m_ogreContext->functions()->glBindBuffer(GL_DRAW_INDIRECT_BUFFER, 0);

**Comment by drewpotter** [comment]
Note, everything builds fine on Linux, but now I am trying OSX...

**Comment by advancingu** [comment]
Sorry, never got around to responding. Did you get the code to work on OSX? I believe some of the GL constants are not available with all platforms and / or drivers.

**Comment by drewpotter** [comment]
I did not manage to get it working on OSX perhaps I can get it to work by changing the code slightly?

**Comment by advancingu** [comment]
Simply try with the failing constants commented out.

**Comment by drewpotter** [comment]
I commented out those lines and it compiles fine.

Then I get the error when linking:
framework not found Ogre

**Comment by advancingu** [comment]
Not sure what that is. Probably it is not finding the Ogre library or the one it finds is not compatible to be linked. I would double-check that Ogre is correctly built and visible to the linker.
